---
title: "Readme"
author: "Chris Bowman"
date: "November 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Getting and Cleaning Data Project

#Initial Comments

This project's purpose is to demonstrate how data can be collected, cleaned, and developed into a "tidy" data set that can be used for other analysis. The data used in this project can be found at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones.

The data for this project can be found here https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI HAR Dataset.zip.

You will need to amend my set working directory command to your own directory.  I have my working directory named as R_Projects.

#Review criterial

1.	The submitted data set is tidy.
2.	The Github repo contains the required scripts.
3.	GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
4.	The README that explains the analysis files is clear and understandable.
5.	The work submitted for this project is the work of the student who submitted it.


#Project Summary

What follows is a summary description of the project instructions
You should create one R script called run_analysis.R that does the following.

1.	Merges the training and the test sets to create one data set.
2.	Extracts only the measurements on the mean and standard deviation for each measurement.
3.	Uses descriptive activity names to name the activities in the data set
4.	Appropriately labels the data set with descriptive variable names.
5.	From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

#Additional Information

All information concerning variables, data, and transformations in the CodeBook.MD file.
